### ISSUE TITLE
Keyboard Shortcut Support Issue

### ISSUE THREAD

**Issue by KevinZonda** [OrbitalShell/Orbital-Shell#41]
**Describe the bug**
The shortcuts is not supported completely. (like Control+C)

**To Reproduce**
1. `ssh xxx@xxx`
2. if `ssh` is waiting for response, `Control-C` will not work,

**Expected behavior**
`Control-C` works

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Comment by franck-gaspoz** [comment]
Hi @KevinZonda ! thanks for your tests and for your feedback.
Effectively there is an issue due to a missing implementation.
when inputing a command that is not part of the orbsh (orbital shell) commands, it try to find a executable or a shell script in the OS (thus the underlying shell).
However, the part of code that execute an os command is not complete : the input stream is not PIPED at all
that's what should be done in order to fix this issue.

the concerned method is:

project OrbitalShell-Kernel, file Component/CommandLine/Processor/CommandLineProcessor.cs , line 577 :

```cs
        public int ShellExec(
            CommandEvaluationContext context,
            string comPath,
            string args,
            string workingDirectory,
            out string output,
            bool waitForExit = true,
            bool isStreamsEchoEnabled = true,
            bool isOutputCaptureEnabled = true,
            bool mergeErrorStreamIntoOutput = true
            )
```

if you are considering to fix this, please remember to assign this ticket to your user.
if you wish to push your results, we will integrate your work after opening a Pull Request and so we will merge
